### ISSUE TITLE
Not working with sapper

### ISSUE THREAD

**Issue by khalld** [6eDesign/svelte-calendar#101]
Hi, on my project on sapper i need to use this plugin.
On a page, between <script> I import:

` import Datepicker from 'svelte-calendar'`

Then, on the html part, for testing if it's working:

`
<Datepicker style="display: block;">
	<button style="width: 100%;">
		FULL WIDTH TRIGGER
	</button>
</Datepicker>
`

But the console says

`
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'svelte-calendar'
Require stack:
- /Users/danilo/svelte-project/LicenseManager/__sapper__/dev/server/server-9ca25463.js
- /Users/danilo/svelte-project/LicenseManager/__sapper__/dev/server/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/danilo/svelte-project/LicenseManager/__sapper__/dev/server/server-9ca25463.js:39:34)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/danilo/svelte-project/LicenseManager/__sapper__/dev/server/server.js:10:1)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/danilo/svelte-project/LicenseManager/__sapper__/dev/server/server-9ca25463.js',
    '/Users/danilo/svelte-project/LicenseManager/__sapper__/dev/server/server.js'
  ]
}`

**Comment by platypusjones** [comment]
You need to include the package in your dependencies: 

`npm i --save svelte-calendar` 

This is a common requirement with sapper, you'll probably run in to it with other packages as well.

**Comment by khalld** [comment]
I already install the module, it give me the same error.

**Comment by khalld** [comment]
Solved, i manually moved from dependecies to devDependecies on package.json

**Comment by platypusjones** [comment]
Cool, in the future, it's worth noting you can do that with NPM as well just by using 

`npm i <package> --save-prod` to add to dependencies, or `npm i <package> --save-dev` to add to dev dependencies. 

This is regardless of if it's installed already, as NPM will check this anyways, and move accordingly.
