### ISSUE TITLE
TypeError: append_styles2 is not a function

### ISSUE THREAD

**Issue by nezlicodes** [6eDesign/svelte-calendar#122]
Hi,

I am getting this error - might be due to switching to **yarn**?- any idea how I can fix this?

```
TypeError: append_styles2 is not a function
    at init (http://localhost:4242/_snowpack/pkg/svelte.internal.v3.40.2.js:1619:21)
    at new Datepicker (http://localhost:4242/_snowpack/pkg/svelte-calendar.v2.0.4.js:2693:3)
    at Array.create_form_slot (http://localhost:4242/dist/features/Home/add-entry/AddEntry.svelte.js:277:15)
    at create_slot (http://localhost:4242/_snowpack/pkg/svelte.internal.v3.40.2.js:69:25)
    at create_fragment (http://localhost:4242/dist/components/entries/EntryBar.svelte.js:43:20)
    at init (http://localhost:4242/_snowpack/pkg/svelte.internal.v3.40.2.js:1634:35)
    at new EntryBar (http://localhost:4242/dist/components/entries/EntryBar.svelte.js:152:3)
    at createProxiedComponent (http://localhost:4242/_snowpack/pkg/svelte-hmr.runtime.hot-api-esm.v0.13.5.js:242:9)
    at new ProxyComponent (http://localhost:4242/_snowpack/pkg/svelte-hmr.runtime.hot-api-esm.v0.13.5.js:482:20)
    at new Proxy<EntryBar> (http://localhost:4242/_snowpack/pkg/svelte-hmr.runtime.hot-api-esm.v0.13.5.js:581:11)
    at Array.create_default_slot (http://localhost:4242/dist/features/Home/add-entry/AddEntry.svelte.js:542:13)
    at create_slot (http://localhost:4242/_snowpack/pkg/svelte.internal.v3.40.2.js:69:25)
    at create_fragment (http://localhost:4242/dist/components/forms/Form.svelte.js:37:23)
    at init (http://localhost:4242/_snowpack/pkg/svelte.internal.v3.40.2.js:1634:35)
    at new Form (http://localhost:4242/dist/components/forms/Form.svelte.js:150:3)
    at createProxiedComponent (http://localhost:4242/_snowpack/pkg/svelte-hmr.runtime.hot-api-esm.v0.13.5.js:242:9)
    at new ProxyComponent (http://localhost:4242/_snowpack/pkg/svelte-hmr.runtime.hot-api-esm.v0.13.5.js:482:20)
    at new Proxy<Form> (http://localhost:4242/_snowpack/pkg/svelte-hmr.runtime.hot-api-esm.v0.13.5.js:581:11)
    at create_fragment (http://localhost:4242/dist/features/Home/add-entry/AddEntry.svelte.js:602:9)
    at init (http://localhost:4242/_snowpack/pkg/svelte.internal.v3.40.2.js:1634:35)
    at new AddEntry (http://localhost:4242/dist/features/Home/add-entry/AddEntry.svelte.js:1014:3)
    at createProxiedComponent (http://localhost:4242/_snowpack/pkg/svelte-hmr.runtime.hot-api-esm.v0.13.5.js:242:9)
    at new ProxyComponent (http://localhost:4242/_snowpack/pkg/svelte-hmr.runtime.hot-api-esm.v0.13.5.js:482:20)
    at new Proxy<AddEntry> (http://localhost:4242/_snowpack/pkg/svelte-hmr.runtime.hot-api-esm.v0.13.5.js:581:11)
    at Object.update [as p] (http://localhost:4242/dist/features/Home/entry-view/EntryView.svelte.js:92:24)
    at update (http://localhost:4242/_snowpack/pkg/svelte.internal.v3.40.2.js:943:32)
    at flush (http://localhost:4242/_snowpack/pkg/svelte.internal.v3.40.2.js:915:7)

```

**Comment by jonathangreenemeier-vizio** [comment]
Did you figure it out then?
