### ISSUE TITLE
3.0.17 - Failed to resolve import "just-throttle" from "node_modules/svelte-calendar/components/generic/KeyControls.svelte". Does the file exist?

### ISSUE THREAD

**Issue by nstuyvesant** [6eDesign/svelte-calendar#127]
Using SvelteKit (latest), I installed svelte-calendar@3.0.17 and added dayjs to my dependencies. Now I'm getting a failure about **just-throttle**.
> 2:59:57 PM [vite] Internal server error: Failed to resolve import "just-throttle" from "node_modules/svelte-calendar/components/generic/KeyControls.svelte". Does the file exist?
>   Plugin: vite:import-analysis
>   File: /Users/nates/dev/shy-svelte/node_modules/svelte-calendar/components/generic/KeyControls.svelte
>   22 |  import { KEY_CODES } from '../../config';
>   23 |  import { keyControlsContextKey } from '../../context';
>   24 |  import throttle from 'just-throttle';
>      |                        ^
>   25 |  import { getContext } from 'svelte';
>   26 |  const file = "node_modules/svelte-calendar/components/generic/KeyControls.svelte";
>       at formatError (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:50143:46)
>       at TransformContext.error (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:50139:19)
>       at normalizeUrl (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:75861:26)
>       at async TransformContext.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:75996:57)
>       at async Object.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:50353:30)
>       at async transformRequest (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:65394:29)
>       at async viteTransformMiddleware (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:65522:32)
> 2:59:58 PM [vite] Internal server error: Failed to resolve import "just-throttle" from "node_modules/svelte-calendar/components/generic/KeyControls.svelte". Does the file exist?
>   Plugin: vite:import-analysis
>   File: /Users/nates/dev/shy-svelte/node_modules/svelte-calendar/components/generic/KeyControls.svelte
>   22 |  import { KEY_CODES } from '../../config';
>   23 |  import { keyControlsContextKey } from '../../context';
>   24 |  import throttle from 'just-throttle';
>      |                        ^
>   25 |  import { getContext } from 'svelte';
>   26 |  const file = "node_modules/svelte-calendar/components/generic/KeyControls.svelte";
>       at formatError (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:50143:46)
>       at TransformContext.error (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:50139:19)
>       at normalizeUrl (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:75861:26)
>       at async TransformContext.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:75996:57)
>       at async Object.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:50353:30)
>       at async transformRequest (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:65394:29)
>       at async viteTransformMiddleware (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:65522:32) (x2)
> 2:59:58 PM [vite] Internal server error: Failed to resolve import "just-throttle" from "node_modules/svelte-calendar/components/generic/KeyControls.svelte". Does the file exist?
>   Plugin: vite:import-analysis
>   File: /Users/nates/dev/shy-svelte/node_modules/svelte-calendar/components/generic/KeyControls.svelte
>   22 |  import { KEY_CODES } from '../../config';
>   23 |  import { keyControlsContextKey } from '../../context';
>   24 |  import throttle from 'just-throttle';
>      |                        ^
>   25 |  import { getContext } from 'svelte';
>   26 |  const file = "node_modules/svelte-calendar/components/generic/KeyControls.svelte";
>       at formatError (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:50143:46)
>       at TransformContext.error (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:50139:19)
>       at normalizeUrl (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:75861:26)
>       at async TransformContext.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:75996:57)
>       at async Object.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:50353:30)
>       at async transformRequest (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:65394:29)
>       at async viteTransformMiddleware (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:65522:32) (x3)
> 2:59:58 PM [vite] Internal server error: Failed to resolve import "just-throttle" from "node_modules/svelte-calendar/components/generic/KeyControls.svelte". Does the file exist?
>   Plugin: vite:import-analysis
>   File: /Users/nates/dev/shy-svelte/node_modules/svelte-calendar/components/generic/KeyControls.svelte
>   22 |  import { KEY_CODES } from '../../config';
>   23 |  import { keyControlsContextKey } from '../../context';
>   24 |  import throttle from 'just-throttle';
>      |                        ^
>   25 |  import { getContext } from 'svelte';
>   26 |  const file = "node_modules/svelte-calendar/components/generic/KeyControls.svelte";
>       at formatError (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:50143:46)
>       at TransformContext.error (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:50139:19)
>       at normalizeUrl (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:75861:26)
>       at async TransformContext.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:75996:57)
>       at async Object.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:50353:30)
>       at async transformRequest (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:65394:29)
>       at async viteTransformMiddleware (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:65522:32) (x4)
> 2:59:58 PM [vite] Internal server error: Failed to resolve import "just-throttle" from "node_modules/svelte-calendar/components/generic/KeyControls.svelte". Does the file exist?
>   Plugin: vite:import-analysis
>   File: /Users/nates/dev/shy-svelte/node_modules/svelte-calendar/components/generic/KeyControls.svelte
>   22 |  import { KEY_CODES } from '../../config';
>   23 |  import { keyControlsContextKey } from '../../context';
>   24 |  import throttle from 'just-throttle';
>      |                        ^
>   25 |  import { getContext } from 'svelte';
>   26 |  const file = "node_modules/svelte-calendar/components/generic/KeyControls.svelte";
>       at formatError (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:50143:46)
>       at TransformContext.error (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:50139:19)
>       at normalizeUrl (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:75861:26)
>       at async TransformContext.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:75996:57)
>       at async Object.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:50353:30)
>       at async transformRequest (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:65394:29)
>       at async viteTransformMiddleware (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:65522:32) (x5)
> 2:59:58 PM [vite] Internal server error: Failed to resolve import "just-throttle" from "node_modules/svelte-calendar/components/generic/KeyControls.svelte". Does the file exist?
>   Plugin: vite:import-analysis
>   File: /Users/nates/dev/shy-svelte/node_modules/svelte-calendar/components/generic/KeyControls.svelte
>   22 |  import { KEY_CODES } from '../../config';
>   23 |  import { keyControlsContextKey } from '../../context';
>   24 |  import throttle from 'just-throttle';
>      |                        ^
>   25 |  import { getContext } from 'svelte';
>   26 |  const file = "node_modules/svelte-calendar/components/generic/KeyControls.svelte";
>       at formatError (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:50143:46)
>       at TransformContext.error (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:50139:19)
>       at normalizeUrl (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:75861:26)
>       at async TransformContext.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:75996:57)
>       at async Object.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:50353:30)
>       at async transformRequest (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:65394:29)
>       at async viteTransformMiddleware (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:65522:32) (x6)
> 2:59:58 PM [vite] Internal server error: Failed to resolve import "just-throttle" from "node_modules/svelte-calendar/components/generic/KeyControls.svelte". Does the file exist?
>   Plugin: vite:import-analysis
>   File: /Users/nates/dev/shy-svelte/node_modules/svelte-calendar/components/generic/KeyControls.svelte
>   22 |  import { KEY_CODES } from '../../config';
>   23 |  import { keyControlsContextKey } from '../../context';
>   24 |  import throttle from 'just-throttle';
>      |                        ^
>   25 |  import { getContext } from 'svelte';
>   26 |  const file = "node_modules/svelte-calendar/components/generic/KeyControls.svelte";
>       at formatError (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:50143:46)
>       at TransformContext.error (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:50139:19)
>       at normalizeUrl (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:75861:26)
>       at async TransformContext.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:75996:57)
>       at async Object.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:50353:30)
>       at async transformRequest (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:65394:29)
>       at async viteTransformMiddleware (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:65522:32) (x7)
> 2:59:58 PM [vite] Internal server error: Failed to resolve import "just-throttle" from "node_modules/svelte-calendar/components/generic/KeyControls.svelte". Does the file exist?
>   Plugin: vite:import-analysis
>   File: /Users/nates/dev/shy-svelte/node_modules/svelte-calendar/components/generic/KeyControls.svelte
>   22 |  import { KEY_CODES } from '../../config';
>   23 |  import { keyControlsContextKey } from '../../context';
>   24 |  import throttle from 'just-throttle';
>      |                        ^
>   25 |  import { getContext } from 'svelte';
>   26 |  const file = "node_modules/svelte-calendar/components/generic/KeyControls.svelte";
>       at formatError (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:50143:46)
>       at TransformContext.error (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:50139:19)
>       at normalizeUrl (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:75861:26)
>       at async TransformContext.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:75996:57)
>       at async Object.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:50353:30)
>       at async transformRequest (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:65394:29)
>       at async viteTransformMiddleware (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-874085d4.js:65522:32) (x8)

After installing just-throttle, I get:

> Importing binding name 'default' cannot be resolved by star export entries.

**Comment by nstuyvesant** [comment]
Resolved in 3.0.19
